application: hrpodcasts
version: 7
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /.*
  script: app.application

libraries:
- name: webapp2
  version: "2.5.2"
